import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { useEffect, useState } from "react";
import { AppNav } from "@/components/app-nav";
import { LoadingView } from "@/components/loading-view";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { analyseAssessment, getDashboard, saveAssessment } from "@/lib/career.functions";
import { assessmentQuestions } from "@/lib/assessment";

export const Route = createFileRoute("/_authenticated/assessment")({ component: AssessmentPage, head: () => ({ meta: [{ title: "Career assessment | Compass" }, { name: "description", content: "Complete your evidence-led RIASEC career interest assessment." }] }) });

function AssessmentPage() {
  const fetchDashboard = useServerFn(getDashboard); const save = useServerFn(saveAssessment); const analyse = useServerFn(analyseAssessment); const navigate = useNavigate();
  const { data, isLoading } = useQuery({ queryKey: ["dashboard"], queryFn: () => fetchDashboard() });
  const [index, setIndex] = useState(0); const [responses, setResponses] = useState<Record<string, number>>({}); const [sessionId, setSessionId] = useState<string>(); const [initialized, setInitialized] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (data && !initialized) { setInitialized(true); if (data.assessment?.status === "in_progress") { setSessionId(data.assessment.id); setResponses((data.assessment.responses ?? {}) as Record<string, number>); setIndex(Math.min(Object.keys((data.assessment.responses ?? {}) as object).length, assessmentQuestions.length - 1)); } } }, [data, initialized]);
  if (isLoading) return <LoadingView/>;
  if (!data?.profile?.display_name) return <div><AppNav/><main className="mx-auto max-w-2xl px-6 py-20 text-center"><h1 className="text-3xl font-bold">First, tell us a little about you.</h1><Button variant="compass" className="mt-6" onClick={() => navigate({ to: "/profile" })}>Complete profile</Button></main></div>;
  const question = assessmentQuestions[index]; const answered = responses[question.id]; const progress = Math.round((Object.keys(responses).length / assessmentQuestions.length) * 100);
  const persist = async (nextResponses = responses) => { const result = await save({ data: { id: sessionId, responses: nextResponses, progress: Math.round((Object.keys(nextResponses).length / assessmentQuestions.length) * 100) } }); setSessionId(result.id); return result.id; };
  const select = async (value: number) => { const next = { ...responses, [question.id]: value }; setResponses(next); setError(""); await persist(next); };
  const finish = async () => { if (Object.keys(responses).length !== assessmentQuestions.length) { setError("Please answer every question before finishing."); return; } setBusy(true); setError(""); try { const id = await persist(); const result = await analyse({ data: { assessmentId: id } }); if (!result.ok) { setError(result.error); return; } navigate({ to: "/dashboard" }); } catch (e) { setError(e instanceof Error ? e.message : "Analysis could not be completed."); } finally { setBusy(false); } };
  return <div className="min-h-screen"><AppNav initials={data.profile.display_name.split(" ").map((v) => v[0]).join("").slice(0, 2).toUpperCase()}/><main className="mx-auto max-w-4xl px-5 py-10 sm:px-6 sm:py-16"><div className="grid gap-8 md:grid-cols-[1fr_190px] md:items-end"><div><p className="font-mono text-[11px] uppercase tracking-widest text-primary">Exploration I · {question.context}</p><h1 className="mt-3 text-4xl font-extrabold tracking-tight sm:text-5xl">Discover how you naturally think and work.</h1></div><div><div className="mb-2 flex justify-between text-xs font-bold uppercase tracking-wider"><span>Progress</span><span className="font-mono">{progress}%</span></div><Progress value={progress} className="h-3 bg-border"/></div></div>
    <section className="mt-12 rounded-2xl border border-border bg-card p-6 sm:p-10"><div className="flex items-center justify-between"><span className="font-mono text-xs text-muted-foreground">{String(index + 1).padStart(2, "0")} / {assessmentQuestions.length}</span><span className="text-xs font-bold uppercase tracking-widest text-muted-foreground">How much is this like you?</span></div><h2 className="mt-8 max-w-2xl text-2xl font-bold leading-snug sm:text-3xl">{question.prompt}</h2><div className="mt-10 grid gap-2 sm:grid-cols-5">{[1,2,3,4,5].map((value) => <Button key={value} type="button" variant={answered === value ? "compass" : "compassOutline"} className="h-auto min-h-20 flex-col whitespace-normal px-2 py-3" onClick={() => select(value)}><span className="font-mono text-lg">{value}</span><span className="text-[10px] font-semibold uppercase tracking-wide">{value === 1 ? "Not like me" : value === 5 ? "Very like me" : value === 3 ? "Unsure" : ""}</span></Button>)}</div><div className="mt-8 flex items-center justify-between gap-4 border-t border-border pt-6"><Button variant="ghost" onClick={() => setIndex(Math.max(0, index - 1))} disabled={index === 0}><ChevronLeft/> Previous</Button>{index < assessmentQuestions.length - 1 ? <Button variant="compass" onClick={() => setIndex(index + 1)} disabled={!answered}>Next <ChevronRight/></Button> : <Button variant="compass" onClick={finish} disabled={!answered || busy}>{busy ? "Analysing your profile…" : "Generate my career path"}</Button>}</div>{error && <p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}</section><p className="mx-auto mt-6 max-w-2xl text-center text-xs leading-relaxed text-muted-foreground">There are no right answers. Your results suggest areas to explore—not limits on what you can achieve.</p></main></div>;
}