import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { FormEvent, useState } from "react";
import { AppNav } from "@/components/app-nav";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { getDashboard, saveProfile } from "@/lib/career.functions";

export const Route = createFileRoute("/_authenticated/profile")({ component: ProfilePage, head: () => ({ meta: [{ title: "Student profile | Compass" }] }) });

function ProfilePage() {
  const fetchDashboard = useServerFn(getDashboard); const save = useServerFn(saveProfile); const navigate = useNavigate();
  const { data, refetch } = useQuery({ queryKey: ["dashboard"], queryFn: () => fetchDashboard() });
  const profile = data?.profile;
  const [form, setForm] = useState({ displayName: "", schoolYear: "", country: "", educationalStage: "secondary" as "lower_secondary" | "secondary" | "sixth_form" | "other", subjects: "" });
  const [initialized, setInitialized] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  if (profile && !initialized) { setInitialized(true); setForm({ displayName: profile.display_name, schoolYear: profile.school_year, country: profile.country, educationalStage: profile.educational_stage as typeof form.educationalStage, subjects: profile.current_subjects.join(", ") }); }
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setMessage(""); try { await save({ data: { displayName: form.displayName, schoolYear: form.schoolYear, country: form.country, educationalStage: form.educationalStage, currentSubjects: form.subjects.split(",").map((s) => s.trim()).filter(Boolean) } }); await refetch(); setMessage("Profile saved."); navigate({ to: "/assessment" }); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save your profile."); } finally { setBusy(false); } };
  return <div className="min-h-screen"><AppNav initials={(form.displayName || "Student").split(" ").map((v) => v[0]).join("").slice(0, 2).toUpperCase()}/><main className="mx-auto max-w-3xl px-5 py-12 sm:px-6"><p className="font-mono text-[11px] uppercase tracking-widest text-primary">Your context</p><h1 className="mt-3 text-4xl font-extrabold tracking-tight sm:text-5xl">Make the guidance yours.</h1><p className="mt-4 max-w-2xl leading-relaxed text-muted-foreground">Your stage, subjects, and location help Compass suggest realistic university routes and next steps. You can change these details at any time.</p>
    <form onSubmit={submit} className="mt-10 grid gap-6 rounded-2xl border border-border bg-card p-6 sm:grid-cols-2 sm:p-8"><label className="text-xs font-bold uppercase tracking-wider">Display name<Input required maxLength={100} className="mt-2 h-11 normal-case" value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })}/></label><label className="text-xs font-bold uppercase tracking-wider">School year<Input required maxLength={50} className="mt-2 h-11 normal-case" placeholder="e.g. Year 11" value={form.schoolYear} onChange={(e) => setForm({ ...form, schoolYear: e.target.value })}/></label><label className="text-xs font-bold uppercase tracking-wider">Country<Input required maxLength={100} className="mt-2 h-11 normal-case" value={form.country} onChange={(e) => setForm({ ...form, country: e.target.value })}/></label><label className="text-xs font-bold uppercase tracking-wider">Education stage<select className="mt-2 h-11 w-full rounded-md border border-input bg-background px-3 text-sm normal-case" value={form.educationalStage} onChange={(e) => setForm({ ...form, educationalStage: e.target.value as typeof form.educationalStage })}><option value="lower_secondary">Lower secondary</option><option value="secondary">Secondary school</option><option value="sixth_form">Sixth form / senior secondary</option><option value="other">Other</option></select></label><label className="text-xs font-bold uppercase tracking-wider sm:col-span-2">Current subjects<Input required maxLength={500} className="mt-2 h-11 normal-case" placeholder="Mathematics, Biology, English…" value={form.subjects} onChange={(e) => setForm({ ...form, subjects: e.target.value })}/><span className="mt-2 block font-normal normal-case tracking-normal text-muted-foreground">Separate subjects with commas.</span></label><div className="sm:col-span-2 flex items-center justify-between gap-4"><p role="status" className="text-sm text-muted-foreground">{message}</p><Button variant="compass" className="h-11 px-6" disabled={busy}>{busy ? "Saving…" : "Save and continue"}</Button></div></form></main></div>;
}