/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUniversityMatcherRouteImport } from './routes/_authenticated/university-matcher'
import { Route as AuthenticatedStatementCoachRouteImport } from './routes/_authenticated/statement-coach'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedRealityCheckerRouteImport } from './routes/_authenticated/reality-checker'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedExplorerRouteImport } from './routes/_authenticated/explorer'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAssessmentRouteImport } from './routes/_authenticated/assessment'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUniversityMatcherRoute =
  AuthenticatedUniversityMatcherRouteImport.update({
    id: '/university-matcher',
    path: '/university-matcher',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatementCoachRoute =
  AuthenticatedStatementCoachRouteImport.update({
    id: '/statement-coach',
    path: '/statement-coach',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRealityCheckerRoute =
  AuthenticatedRealityCheckerRouteImport.update({
    id: '/reality-checker',
    path: '/reality-checker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExplorerRoute = AuthenticatedExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentRoute = AuthenticatedAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/explorer': typeof AuthenticatedExplorerRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reality-checker': typeof AuthenticatedRealityCheckerRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/statement-coach': typeof AuthenticatedStatementCoachRoute
  '/university-matcher': typeof AuthenticatedUniversityMatcherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/explorer': typeof AuthenticatedExplorerRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reality-checker': typeof AuthenticatedRealityCheckerRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/statement-coach': typeof AuthenticatedStatementCoachRoute
  '/university-matcher': typeof AuthenticatedUniversityMatcherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/assessment': typeof AuthenticatedAssessmentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/explorer': typeof AuthenticatedExplorerRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reality-checker': typeof AuthenticatedRealityCheckerRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/statement-coach': typeof AuthenticatedStatementCoachRoute
  '/_authenticated/university-matcher': typeof AuthenticatedUniversityMatcherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/assessment'
    | '/dashboard'
    | '/explorer'
    | '/feedback'
    | '/profile'
    | '/reality-checker'
    | '/roadmap'
    | '/statement-coach'
    | '/university-matcher'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/assessment'
    | '/dashboard'
    | '/explorer'
    | '/feedback'
    | '/profile'
    | '/reality-checker'
    | '/roadmap'
    | '/statement-coach'
    | '/university-matcher'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/assessment'
    | '/_authenticated/dashboard'
    | '/_authenticated/explorer'
    | '/_authenticated/feedback'
    | '/_authenticated/profile'
    | '/_authenticated/reality-checker'
    | '/_authenticated/roadmap'
    | '/_authenticated/statement-coach'
    | '/_authenticated/university-matcher'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/university-matcher': {
      id: '/_authenticated/university-matcher'
      path: '/university-matcher'
      fullPath: '/university-matcher'
      preLoaderRoute: typeof AuthenticatedUniversityMatcherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statement-coach': {
      id: '/_authenticated/statement-coach'
      path: '/statement-coach'
      fullPath: '/statement-coach'
      preLoaderRoute: typeof AuthenticatedStatementCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reality-checker': {
      id: '/_authenticated/reality-checker'
      path: '/reality-checker'
      fullPath: '/reality-checker'
      preLoaderRoute: typeof AuthenticatedRealityCheckerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explorer': {
      id: '/_authenticated/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof AuthenticatedExplorerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment': {
      id: '/_authenticated/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AuthenticatedAssessmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssessmentRoute: typeof AuthenticatedAssessmentRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExplorerRoute: typeof AuthenticatedExplorerRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRealityCheckerRoute: typeof AuthenticatedRealityCheckerRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedStatementCoachRoute: typeof AuthenticatedStatementCoachRoute
  AuthenticatedUniversityMatcherRoute: typeof AuthenticatedUniversityMatcherRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssessmentRoute: AuthenticatedAssessmentRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExplorerRoute: AuthenticatedExplorerRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRealityCheckerRoute: AuthenticatedRealityCheckerRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedStatementCoachRoute: AuthenticatedStatementCoachRoute,
  AuthenticatedUniversityMatcherRoute: AuthenticatedUniversityMatcherRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
